// BPHS bhaavesha-phala - effects of each house-LORD placed in each house
// (144 combinations, BPHS Chapters 12-23). Auto-extracted from the Brihat
// Parasara Hora Sastra text; keyed BPHS_LORD_IN_HOUSE[lordOfHouse][placedInHouse].

export const BPHS_LORD_IN_HOUSE: Record<number, Record<number, string>> = {
  1: {
    1: "Should Lagns Lord be in Lagn itself, the native will be endowed with physical happiness and prowess. He will be intelligent, fickle-minded, will have two wives and will unite with other females.",
    2: "If the Lagns Lord is in Dhan, he will be gainful, scholarly, happy, endowed with good qualities, be religious, honourable and will have many wives.",
    3: "If Lagns Lord is in Sahaj Bhava, the native will equal a lion in valour, be endowed with all kinds of wealth, be honourable, will have two wives, be intelligent and happy.",
    4: "If Lagns Lord is in Bandhu Bhava, the native will be endowed with paternal and maternal happiness, will have many brothers, be lustful, virtuous and charming.",
    5: "If Lagns Lord is in Putr Bhava, the native will have mediocre progenic happiness, will lose his first child, be honourable, given to anger and be dear to king.",
    6: "If Lagns Lord is in Ari Bhava and related to a malefic the native will be devoid of physical happiness and will be troubled by enemies, if there is no benefic Drishti.",
    7: "If Lagns Lord is a malefic and is placed in Yuvati Bhava, the natives wife will not live (long). If the Grah in question is a benefic, one will wander aimlessly, face penury and be dejected. He will alternatively become a king (if the said Grah is strong).",
    8: "If Lagns Lord is in Randhr Bhava, the native will be an accomplished scholar, be sickly, thievish, be given to much anger, be a gambler and will join others wives.",
    9: "If Lagns Lord is in Dharm Bhava, the native will be fortunate, dear to people, be a devotee of r Vishnu, be skilful, eloquent in speech and be endowed with wife, sons and wealth.",
    10: "If Lagns Lord is in Karm Bhava, the native will be endowed with paternal happiness, royal honour, fame among men and will doubtlessly have self-earned wealth.",
    11: "If Lagns Lord is in Labh Bhava, the native will always be endowed with gains, good qualities, fame and many wives.",
    12: "If Lagns Lord is in Vyaya Bhava and is devoid of benefic Drishti and/or Yuti, the native will be bereft of physical happiness, will spend unfruitfully and be given to much anger.",
  },
  2: {
    1: "If Dhans Lord is in Tanu Bhava, the native will be endowed with sons and wealth, be inimical to his family, lustful, hard-hearted and will do others jobs.",
    2: "If Dhans Lord is in Dhan Bhava, the native will be wealthy, proud, will have two, or more wives and be bereft of progeny.",
    3: "If Dhans Lord is in Sahaj Bhava, the native will be valorous, wise, virtuous, lustful and miserly; all these, when related to a benefic. If related to a malefic, the native will be a heterodox.",
    4: "If Dhans Lord is in Bandhu Bhava, the native will acquire all kinds of wealth. If Dhans Lord is exalted and is yuti with Guru, one will be equal to a king.",
    5: "If Dhans Lord is in Putr Bhava, the native will be wealthy. Not only the native, but also his sons will be intent on earning wealth.",
    6: "If Dhans Lord is in Ari Bhava along with a benefic, the native will gain wealth through his enemies; if Dhans Lord is yuti with a malefic, there will be loss through enemies apart from mutilation of shanks.",
    7: "If Dhans Lord is in Yuvati Bhava, the native will be addicted to others wives and he will be a doctor. If a malefic is related to the said placement by yuti with Dhans Lord, or by Drishti, the natives wife will be of questionable character.",
    8: "If Dhans Lord is in Randhr Bhava, the native will be endowed with abundant land and wealth. But he will have limited marital felicity and be bereft of happiness from his elder brother.",
    9: "If Dhans Lord is in Dharm Bhava, the native will be wealthy, diligent, skilful, sick during childhood and will later on be happy and will visit shrines, observing religious code etc.",
    10: "If Dhans Lord is in Karm Bhava, the native will be libidinous, honourable and learned; he will have many wives and much wealth, but he will be bereft of filial happiness.",
    11: "If Dhans Lord is in Labh Bhava, the native will have all kinds of wealth, be ever diligent, honourable and famous.",
    12: "If Dhans Lord is in Vyaya Bhava, the native will be adventurous, be devoid of wealth and be interested in others wealth, while his eldest child will not keep him happy.",
  },
  3: {
    1: "If Sahajs Lord is in Tanu Bhava, the native will have self-made wealth, be disposed to worship, be valorous and be intelligent, although devoid of learning.",
    2: "If Sahajs Lord is in Dhan Bhava, the native will be corpulent, devoid of valour, will not make much efforts, be not happy and will have an eye on others wives and others wealth.",
    3: "If Sahajs Lord is in Sahaj Bhava, the native will be endowed with happiness through co-born and will have wealth and sons, be cheerful and extremely happy.",
    4: "If Sahajs Lord is in Bandhu Bhava, the native will be happy, wealthy and intelligent, but will acquire a wicked spouse.",
    5: "If Sahajs Lord is in Putr Bhava, the native will have sons and be virtuous. If in the process Sahajs Lord be yuti with, or receives a Drishti from a malefic, the native will have a formidable wife.",
    6: "If Sahajs Lord is in Ari Bhava, the native will be inimical to his co-born, be affluent, will not be well disposed to his maternal uncle and be dear to his maternal aunt.",
    7: "If Sahajs Lord is in Yuvati Bhava, the native will be interested in serving the king. He will not be happy during boyhood, but the end of his life he will be happy.",
    8: "If Sahajs Lord is in Randhr Bhava, the native will be a thief, will derive his livelihood serving others and will die at the gate of the royal palace.",
    9: "If Sahajs Lord is in Dharm Bhava, the native will lack paternal bliss, will make fortunes through wife and will enjoy progenic and other pleasures.",
    10: "If Sahajs Lord is in Karm Bhava, the native will have all lands of happiness and self-made wealth and be interested in nurturing wicked females.",
    11: "If Sahajs Lord is in Labh Bhava, then native will always gain in trading, be intelligent, although not literate, be adventurous and will serve others.",
    12: "If Sahajs Lord is in Vyaya, the native will spend on evil deeds, will have a wicked father and will be fortunate through a female.",
  },
  4: {
    1: "If Bandhus Lord is in Tanu Bhava, the native will be endowed with learning, virtues, ornaments, lands, conveyances and maternal happiness.",
    2: "If Bandhus Lord is in Dhan Bhava, the native will enjoy pleasures, all kinds of wealth, family life and honour and be adventurous. He will be cunning in disposition.",
    3: "If Bandhus Lord is in Sahaj Bhava, the native will be valorous, will have servants, be liberal, virtuous and charitable and will possess self-earned wealth. He will be free from diseases.",
    4: "If Bandhus Lord is in Bandhu, the native will be a minister and will possess all kinds of wealth. He will be skilful, virtuous, honourable, learned, happy and be well disposed to his spouse.",
    5: "If Bandhus Lord is in Putr Bhava, the native will be happy and be liked by all. He will be devoted to r Vishnu, be virtuous, honourable and will have self-earned wealth.",
    6: "If Bandhus Lord is in Ari Bhava, the native will be devoid of maternal happiness, be given to anger, be a thief and a conjurer, be independent in action and be indisposed.",
    7: "If Bandhus Lord is in Yuvati Bhava, the native will be endowed with a high degree of education, will sacrifice his patrimony and be akin to the dumb in an assembly.",
    8: "If Bandhus Lord is in Randhr Bhava, the native will be devoid of domestic and other comforts, will not enjoy much parental happiness and be equal to a neuter.",
    9: "If Bandhus Lord is in Dharm Bhava, the native will be dear to one and all, be devoted to God, be virtuous, honourable and endowed with every land of happiness.",
    10: "If Bandhus Lord is in Karm Bhava, the native will enjoy royal honours, be an alchemist, be extremely pleased, will enjoy pleasures and will conquer his five senses.",
    11: "If Bandhus Lord is in Labh Bhava, the native will have fear of secret disease, he will be liberal, virtuous, charitable and helpful to others.",
    12: "If Bandhus Lord is in Vyaya Bhava the native will be devoid of domestic and other comforts, will have vices and be foolish and indolent.",
  },
  5: {
    1: "If Putrs Lord is in Lagn, the native will be scholarly, be endowed with progenic happiness, be a miser, be crooked and will steal others wealth.",
    2: "If Putrs Lord is in Dhan Bhava, the native will have many sons and wealth, be a pater familias, be honourable, be attached to his spouse and be famous in the world.",
    3: "If Putrs Lord is in Sahaj, the native will be attached to his co-born, be a tale bearer and a miser and be always interested in his own work.",
    4: "If Putrs Lord is in Bandhu Bhava, the native will be happy, endowed with maternal happiness, wealth and intelligence and be a king, or a minister, or a preceptor.",
    5: "If Putrs Lord is in Putr Bhava, the native will have progeny, if related to a benefic; there will be no issues, if malefic is related to Putrs Lord, placed in Putr Bhava. Putrs Lord in Putr Bhava will, however, make one virtuous and dear to friends.",
    6: "If Putrs Lord is in Ari Bhava, the native will obtain such sons, who will be equal to his enemies, or will lose them, or will acquire an adopted, or purchased son.",
    7: "If Putrs Lord is in Yuvati Bhava, the native will be honourable, very religious, endowed with progenic happiness and be helpful to others.",
    8: "If Putrs Lord is in Randhr Bhava, the native will not have much progenic happiness, be troubled by cough and pulmonary disorders, be given to anger and be devoid of happiness.",
    9: "If Putrs Lord is in Dharm Bhava, the native will be a prince, or equal to him, will author treatises, be famous and will shine in his race.",
    10: "If Putrs Lord is in Karm Bhava, the native will enjoy a Raj Yog and various pleasures and be very famous.",
    11: "If Putrs Lord is in Labh Bhava, the native will be learned, dear to people, be an author of treatises, be very skilful and be endowed with many sons and wealth.",
    12: "If Putrs Lord is in Vyaya Bhava, the native will be bereft of happiness from his own sons, will have an adopted, or purchased son.",
  },
  6: {
    1: "If Aris Lord is in Tanu Bhava, the native will be sickly, famous, inimical to his own men, rich, honourable, adventurous and virtuous.",
    2: "If Aris Lord is in Dhan Bhava, the native will be adventurous, famous among his people, will live in alien countries, be happy, be a skilful speaker and be always interested in his own work.",
    3: "If Aris Lord is in Sahaj Bhava, the native will be given to anger, be bereft of courage, inimical to all of his co-born and will have disobedient servants.",
    4: "If Aris Lord is in Bandhu Bhava, the native will be devoid maternal happiness, be intelligent, be a tale bearer, be jealous, evil-minded and very rich.",
    5: "If Aris Lord is in Putr Bhava, the native will have fluctuating finances. He will incur enmity with his sons and friends. He will be happy, selfish and kind.",
    6: "If Aris Lord is in Ari Bhava, the native will have enmity with the group of his kinsmen, but be friendly to others and will enjoy mediocre happiness in matters, like wealth.",
    7: "If Aris Lord is in Yuvati Bhava, the native will be deprived of happiness through wedlock. He will be famous, virtuous, honourable, adventurous and wealthy.",
    8: "If Aris Lord is in Randhr Bhava, the native will be sickly, inimical, will desire others wealth, be interested in others wives and be impure.",
    9: "If Aris Lord is in Dharm Bhava, the native will trade in wood and stones (,,Pashan also means poison) and will have fluctuating professional fortunes.",
    10: "If Aris Lord is in Karm Bhava, the native will be well known among his men, will not be respectfully disposed to his father and will be happy in foreign countries. He will be a gifted speaker.",
    11: "If Aris Lord is in Labh Bhava, the native will gain wealth through his enemies, be virtuous, adventurous and will be somewhat bereft of progenic happiness.",
    12: "If Aris Lord is in Vyaya Bhava, the native will always spend on vices, be hostile to learned people and will torture living beings.",
  },
  7: {
    1: "If Yuvatis Lord is in Tanu Bhava, the native will go to others wives, be wicked, skilful, devoid of courage and afflicted by windy diseases.",
    2: "If Yuvatis Lord is in Dhan Bhava, the native will have many wives, will gain wealth through his wife and be procrastinating in nature.",
    3: "If Yuvatis Lord is in Sahaj Bhava, the native will face loss of children and sometimes with great difficulty there will exist a living son. There is also the possibility of birth of a daughter.",
    4: "If Yuvatis Lord is in Bandhu Bhava, the wife of the native will not be under his control. He will be fond of truth, intelligent and religious. He will suffer from dental diseases.",
    5: "If Yuvatis Lord is in Putr Bhava, the native will be honourable, endowed with all (i.e. seven principal) virtues, always delighted and endowed with all kinds of wealth.",
    6: "If Yuvatis Lord is in Ari Bhava, the native will beget a sickly wife and he will be inimical to her. He will be given to anger and will be devoid of happiness.",
    7: "If Yuvatis Lord is in Yuvati Bhava, the native will be endowed with happiness through wife, be courageous, skilful and intelligent, but only afflicted by windy diseases.",
    8: "If Yuvatis Lord is in Randhr Bhava, the native will be deprived of marital happiness. His wife will be troubled by diseases, be devoid of good disposition and will not obey the native.",
    9: "If Yuvatis Lord is in Dharm Bhava, the native will have union with many women, be well disposed to his own wife and will have many undertakings.",
    10: "If Yuvatis Lord is in Karm Bhava, the native will beget a disobedient wife, will be religious and endowed with wealth, sons etc.",
    11: "If Yuvatis Lord is in Labh Bhava, the native will gain wealth through his wife, be endowed with less happiness from sons etc. and will have daughters.",
    12: "If Yuvatis Lord is in Vyaya Bhava, the native will incur penury, be a miser and his livelihood will be related to clothes. His wife will be a spendthrift.",
  },
  8: {
    1: "If Randhrs Lord is in Tanu Bhava, the native will be devoid of physical felicity and will suffer from wounds. He will be hostile to gods and Brahmins.",
    2: "If Randhrs Lord is in Dhan Bhava, the native will be devoid of bodily vigour, will enjoy a little wealth and will not regain lost wealth.",
    3: "If Randhrs Lord is in Sahaj Bhava, the native will be devoid of fraternal happiness, be indolent and devoid of servants and strength.",
    4: "If Randhrs Lord is in Bandhu Bhava, the child will be deprived of its mother. He will be devoid of a house, lands and happiness and will doubtlessly betray his friends.",
    5: "If Randhrs Lord is in Putr Bhava, the native will be dull witted, will have limited number of children, be long-lived and wealthy.",
    6: "If Randhrs Lord is in Ari Bhava, the native will win over his enemies, be afflicted by diseases and during childhood will incur danger through snakes and water.",
    7: "If Randhrs Lord is in Yuvati Bhava, the native will have two wives. If Randhrs Lord is yuti with a malefic in Yuvati Bhava, there will surely be downfall in his business.",
    8: "If Randhrs Lord is in Randhr Bhava, the native will be long-lived. If the said Grah is weak, being in Randhr Bhava, the longevity will be medium, while the native will be a thief, be blameworthy and will blame others as well.",
    9: "If Randhrs Lord is in Dharm Bhava, the native will betray his religion, be a heterodox, will beget a wicked wife and will steal others wealth.",
    10: "If Randhrs Lord is in Karm Bhava, the native will be devoid of paternal bliss, be a talebearer and be bereft of livelihood. If there is a Drishti in the process from a benefic, then these evils will not mature.",
    11: "If Randhrs Lord along with a malefic is in Labh Bhava, the native will be devoid of wealth and will be miserable in boyhood, but happy later on. Should Randhrs Lord be yuti with a benefic and be in Labh Bhava, the native will be long-lived.",
    12: "If Randhrs Lord is in Vyaya Bhava, the native will spend on evil deeds and will incur a short life. More so, if there be additionally a malefic in the said Bhava.",
  },
  9: {
    1: "If Dharms Lord is in Lagn, the native will be fortunate, will be honoured by the king, be virtuous, charming, learned and honoured by the public.",
    2: "If Dharms Lord is in Dhan Bhava, the native will be a scholar, be dear to all, wealthy, sensuous and endowed with happiness from wife, sons etc.",
    3: "If Dharms Lord is in Sahaj Bhava, the native will be endowed with fraternal bliss, be wealthy, virtuous and charming.",
    4: "If Dharms Lord is in Bandhu Bhava, the native will enjoy houses, conveyances and happiness, will have all kinds of wealth and be devoted to his mother.",
    5: "If Dharms Lord is in Putr Bhava, the native will be endowed with sons and prosperity, devoted to elders, bold, charitable and learned.",
    6: "If Dharms Lord is in Ari Bhava, the native will enjoy meagre prosperity, be devoid of happiness from maternal relatives and be always troubled by enemies.",
    7: "O Brahmin, If Dharms Lord is in Yuvati Bhava, the native beget happiness after marriage, be virtuous and famous.",
    8: "If Dharms Lord is in Randhr Bhava, the native will not be prosperous and will not enjoy happiness from his elder brother.",
    9: "If Dharms Lord is in Dharm Bhava, the native will be endowed with abundant fortunes, virtues and beauty and will enjoy much happiness from co-born.",
    10: "If Dharms Lord is in Karm Bhava, the native will be a king, or equal to him, or be a minister, or an Army chief, be virtuous and dear to all.",
    11: "If Dharms Lord is in Labh Bhava, the native will enjoy financial gains day by day, be devoted to elders, virtuous and meritorious in acts.",
    12: "If Dharms Lord is in Vyaya Bhava, the native will incur loss of fortunes, will always spend on auspicious acts and will become poor on account of entertaining guests.",
  },
  10: {
    1: "If Karms Lord is in Tanu Bhava, the native will be scholarly, famous, be a poet, will incur diseases in boyhood and be happy later on. His wealth will increase day by day.",
    2: "If Karms Lord is in Dhan Bhava, the native will be wealthy, virtuous, honoured by the king, charitable and will enjoy happiness from father and others.",
    3: "If Karms Lord is in Sahaj Bhava, the native will enjoy happiness from brothers and servants, be valorous, virtuous, eloquent and truthful.",
    4: "If Karms Lord is in Bandhu Bhava, the native will be happy, be always interested in his mothers welfare, will Lord over conveyances, lands and houses, be virtuous and wealthy.",
    5: "If Karms Lord is in Putr Bhava, the native will be endowed with all kinds of learning, he will be always delighted and he will be wealthy and endowed with sons.",
    6: "If Karms Lord is in Ari Bhava, the native will be bereft of paternal bliss. Although he may be skilful, he will be bereft of wealth and be troubled by enemies.",
    7: "If Karms Lord is in Yuvati Bhava, the native will be endowed with happiness through wife, be intelligent, virtuous, eloquent, truthful and religious.",
    8: "If Karms Lord is in Randhr Bhava, the native will be devoid of acts, long-lived and intent on blaming others.",
    9: "If Karms Lord is in Dharm Bhava, one born of royal scion will become a king, whereas an ordinary native will be equal to a king. This placement will confer wealth and progenic happiness etc.",
    10: "If Karms Lord is in Karm Bhava, the native will be skilful in all jobs, be valorous, truthful and devoted to elders.",
    11: "If Karms Lord is in Labh Bhava, the native will be endowed with wealth, happiness and sons. He will be virtuous, truthful and always delighted.",
    12: "If Karms Lord is in Vyaya Bhava, the native will spend through royal abodes, will have fear from enemies and will be worried in spite of being skilful.",
  },
  11: {
    1: "If Labhs Lord is in Tanu Bhava, the native will be genuine in disposition, be rich, happy, even-sighted, be a poet, be eloquent in speech and be always endowed with gains.",
    2: "If Labhs Lord is in Dhan Bhava, the native will be endowed with all kinds of wealth and all kinds of accomplishments, charitable, religious and always happy.",
    3: "If Labhs Lord is in Sahaj Bhava, the native will be skilful in all jobs, wealthy, endowed with fraternal bliss and may sometimes incur gout pains.",
    4: "If Labhs Lord is in Bandhu Bhava, the native will gain from maternal relatives, will undertake visits to shrines and will possess happiness of house and lands.",
    5: "If Labhs Lord is in Putr Bhava, the native will be happy, educated and virtuous. He will be religious and happy.",
    6: "If Labhs Lord is in Ari Bhava, the native will be afflicted by diseases, be cruel, living in foreign places and troubled by enemies.",
    7: "If Labhs Lord is in Yuvati Bhava, the native will always gain through his wifes relatives, be liberal, virtuous, sensuous and will remain at the command of his spouse.",
    8: "If Labhs Lord is in Randhr Bhava, the native will incur reversals in his undertakings and will live long, while his wife will predecease him.",
    9: "If Labhs Lord is in Dharm Bhava, the native will be fortunate, skilful, truthful, honoured by the king and be affluent.",
    10: "If Labhs Lord is in Karm Bhava, the native will be honoured by the king, be virtuous, attached to his religion, intelligent, truthful and will subdue his senses.",
    11: "If Labhs Lord is in Labh Bhava, the native will gain in all his undertakings, while his learning and happiness will be on the increase day by day.",
    12: "If Labhs Lord is in Vyaya Bhava, the native will always depend on good deeds, be sensuous, will have many wives and will befriend barbarians.",
  },
  12: {
    1: "If Vyayas Lord is in Tanu Bhava, the native will be a spendthrift, be weak in",
    2: "If Vyayas Lord is in Dhan Bhava, the native will always spend on inauspicious deeds, be religious, will speak sweetly and will be endowed with virtues and happiness.",
    3: "If Vyayas Lord is in Sahaj Bhava, the native will be devoid of fraternal bliss, will hate others and will promote self-nourishment.",
    4: "If Vyayas Lord is in Bandhu Bhava, the native will be devoid of maternal happiness and will day by day accrue losses with respect to lands, conveyances and houses.",
    5: "If Vyayas Lord is in Putr Bhava, the native will be bereft of sons and learning. He will spend, as well as visit shrines in order to beget a son.",
    6: "If Vyayas Lord is in Ari Bhava, the native will incur enmity with his own men, be given to anger, be sinful, miserable and will go to others wives.",
    7: "If Vyayas Lord is in Yuvati Bhava, the native will incur expenditure on account of his wife, will not enjoy conjugal bliss and will be bereft of learning and strength.",
    8: "If Vyayas Lord is in Randhr Bhava, the native will always gain, will speak affably, will enjoy a medium span of life and be endowed with all good qualities.",
    9: "If Vyayas Lord is in Dharm Bhava, the native will dishonour his elders, be inimical even to his friends and be always intent on achieving his own ends.",
    10: "If Vyayas Lord is in Karm Bhava, the native will incur expenditure through royal persons and will enjoy only moderate paternal bliss.",
    11: "If Vyaya Lord is in Labh Bhava, the native will incur losses, be brought up by others and will sometimes gain through others.",
    12: "If Vyayas Lord is in Vyaya Bhava, the native will only face heavy expenditure, will not have physical felicity, be irritable and spiteful.",
  },
};
