// BPHS antardaśā-phala — effects of each antar-lord within each mahādaśā
// (BPHS Ch. 52-60). Auto-extracted; keyed DASHA_ANTAR[mahaLord][antarLord].
import type { PlanetName } from "./constants";

export const DASHA_ANTAR: Partial<Record<PlanetName, Partial<Record<PlanetName, string>>>> = {
  Sun: {
    Moon: "If Candr is in a Kendr, or in a Trikon. There will be marriage of the native, birth of children, beneficence of and favours from kings and fulfillment of all ambitions, if Candr is in his exaltation Ri, or in his own Ri.",
    Mars: "If Mangal is in his exaltation Ri, in his own Ri, in a Kendr, or in a Trikon. All-round gains, attainment of the position of a Commander of the Army, destruction of enemies, peace of mind, family comforts and increase in the number of co-borns will be the effects, if Mangal is yuti with the Lagns Lord.",
    Mercury: "If Budh is in a Kendr, or in a Trikon from Lagn.",
    Jupiter: "If Guru is in a Kendr, or in a Trikon to Lagn, in his exaltation Ri, in his own Ri, or in his own Varg.",
    Venus: "If ukr is placed in a Kendr, or in a Trikon, or, if ukr is in his exaltation Ri, in his own Ri, in his own Varg, or in a friendly Ri.",
    Saturn: "If ani is in a Kendr, or in a Trikon from Lagn. Well-being, acquisition of more property, recognition by the king, achievement of renown in the country, gain of wealth from many sources will be the effects, if ani is in his exaltation, in his own, in a friendly Ri and, if ani is yuti with a friendly Grah.",
    Rahu: "If Rahu is in a Kendr, or in a Trikon from Lagn, there will be in the first two months loss of wealth, danger from thieves, snakes, infliction of wounds and distress to wife and children. After 2 months inauspicious effects will disappear and enjoyment and comforts, sound health, satisfaction, favours from the king and government etc.",
    Ketu: ". If Ketu is associated with the Lord of Lagn, there will be some happiness at the commencement, distress in the middle part and receipt of the news of death at the end of the Antar Dasha.",
  },
  Moon: {
    Sun: "If Srya is in his exaltation Ri, in his own Ri, in a Kendr, or in Putr, or in Dharm, or in Labh, or in Dhan, or in Sahaj. At the end of the Antar Dasha there is the likelihood of attacks of fever and lethargy.",
    Mars: "If Mangal is in a Kendr, or in a Trikon. Great happiness and enjoyment of comforts will be derived, if Mangal is in his exaltation Ri, or in his own Ri.",
    Mercury: "If Budh is in a Kendr, or in a Trikon, if Budh is in his own Ri, in his own Nav, or in his exaltation Ri, endowed with strength.",
    Jupiter: "If Guru is placed in a Kendr, or in a Trikon to Lagn, or, if Guru is in his own, or in his exaltation Ri.",
    Venus: "If ukr is in a Kendr, in a Trikon, in Labh, Bandhu, or Dharm, or in his exaltation Ri, or in his own Ri.",
    Saturn: "If ani is in a Kendr, or in a Trikon from Lagn, or, if ani is in his own Ri, in his own Nav, in his exaltation Ri, if ani receives a Drishti from, or is associated with benefics, or, if ani is in Labh with strength.",
    Rahu: "But later there will be danger from the king, thieves and snakes, distress to cattle, loss of kinsmen and friends, loss of reputation and mental agony, if Rahu is placed in a Kendr, or in a Trikon.",
    Ketu: "If Ketu is in a Kendr, in a Trikon, or Sahaj and is endowed with strength. There will be some loss of wealth at the commencement of the Antar Dasha.",
  },
  Mars: {
    Sun: "If Srya is in his exaltation, in his own Ri, or, if Srya is in a Kendr, in a Trikon, or in Labh along with Karms Lord and with Labhs Lord.",
    Moon: "If Candr is in her exaltation Ri, or in her own Ri, or in a Kendr, or in Dharm, or in Bandhu, or in Karm, or in Lagn along with the Lords of those Bhavas. The good effects will be realized in full, if Candr is waxing.",
    Mercury: "If Budh is in a Kendr, or in a Trikon from Lagn.",
    Jupiter: "If Guru is in Dharm, or Putr, in a Kendr, or in Labh, or in Dhan, or, if Guru is in his exalted, or own Nav.",
    Venus: "If ukr is in a Kendr to Lagn, if ukr is in his exaltation, or in his own Ri, or, if ukr is Lagns, Putrs, or Dharms Lord. If ukr is related to Lagns Lord, there will be happiness to wife and children, opulence and glory and increased good fortune.",
    Saturn: "If ani is in a Kendr, in a Trikon, in his Multrikon, in his exalted, or his own Nav, or, if ani is associated with the Lord of Lagn, or, if ani is associated with benefics. Results will generally fructify on Saturdays in the month of ani.",
    Rahu: "If Rahu is in his Multrikon, in his exaltation Ri, in a Kendr, in Labh, Putr, or Dharm and is associated with benefics.",
    Ketu: "If Ketu is in a Kendr, in a Trikon, in Sahaj, or Labh, or, if Ketu is associated with, or receives a Drishti from benefics.",
  },
  Mercury: {
    Sun: "If Srya is in his own, or in his exaltation Ri, or in a Kendr, or Trikon, or in Dhan, or Labh, or in his exalted, or own Nav. There will be acquisition of land, if Srya receives a Drishti from Mangal and comforts of good food and clothes, if such a Srya receives a Drishti from Lagns Lord.",
    Moon: "Candr is in a Kendr, or Trikon from Lagn, or, if Candr is in her exaltation, or in her own Ri, associated with, or receiving a Drishti from Guru, or, if Candr is a Yog Karak herself. Then there will be marriage, birth of a son and gain of clothes and ornaments.",
    Mars: "If Mangal is in his exaltation, in his own Ri, in a Kendr, or Trikon, or, if Mangal is asociated with Lagns Lord.",
    Jupiter: "If Guru is in a Kendr, Trikon, or in Labh, or, if Guru is in his exaltation, or in his own Ri.",
    Venus: "If ukr is in a Kendr, in Labh, in Putr, or in Dharm. There will be acquisition of a kingdom, gain of wealth and property, construction of a reservoir, readiness to give charities and to perform religious rites, extraordinary gain of wealth and gains in business, if ukr is in a Kendr, in the 5th, 9th, or 11th from the Lord of the Dasha.",
    Saturn: "If ani is in his exaltation, his in his own Ri, or in a Kendr, or Trikon, or in Labh.",
    Rahu: "If Rahu is in a Kendr, or Trikon, or, if Rahu is in Mesh, Kumbh, Kanya, or Vrishabh. There will be some evil effects at the commencement of the Antar Dasha, but all will be well later.",
  },
  Jupiter: {
    Sun: "If Srya is in his exaltation, in his own Ri, in a Kendr, Trikon, or in Sahaj, Labh, or Dhan and be endowed with strength.",
    Moon: "If Candr is in a Kendr, Trikon, or in Labh, or, if Candr is in her exaltation, or in her own Ri and, if Candr is full and strong and in an auspicious Bhava from the Lord of the Dasha.",
    Mars: "If Mangal is in his exaltation, in his own Ri, or in his exalted, or own Nav.",
    Mercury: "If Budh is in his exaltation, in his own Ri, or in Kendr, in Trikon, or, if Budh is associated with the Lord of the Dasha.",
    Saturn: "If ani is in his exaltation, in his own Ri, in a Kendr, or Trikon endowed with strength.",
    Rahu: "If Rahu is in his exaltation, in his own Ri, in his Multrikon, or, if Rahu is in a Kendr, or Trikon, or, if Rahu receives a Drishti from the Lord of a Kendr, or, if Rahu is associated with, or receives a Drishti from a benefic.",
    Ketu: "If Ketu is associated with, or receives a Drishti from a benefic.",
  },
  Venus: {
    Sun: "If Srya is in any Ri, other than his exaltation, or debilitation Ri. (This verse does not appear to be correctly worded, because Srya does produce good effects in a position, other than exaltation, or debilitation.",
    Moon: "If Candr is in her exaltation, or in her own Ri, or is associated with the Lord of Dharm, benefics, or with Karms Lord, or, if Candr is in a Kendr, Trikon, or Labh.",
    Mars: "If Mangal is in a Kendr, or Trikon, or in Labh, or, if Mangal is in his exaltation Ri, or is in one of his own Ris, or is associated with the Lagns, Dharms, or Karms Lord.",
    Mercury: "If Budh is in a Kendr, or Trikon, or in Labh (from Lagn, or from the Lord of the Dasha), or is in his exaltation, or in his own Ri.",
    Jupiter: "If Guru is in his exaltation, in his own Ri, or in a Kendr, or Trikon to Lagn, or to the Lord of the Dasha.",
    Saturn: "If ani is in his exaltation, in his own Ri, in a Kendr, Trikon, or in his own Nav.",
    Rahu: "If Rahu is in a Kendr, or Trikon, or in Labh, or, if Rahu is in his exaltation, or in his own Ri, or is associated with, or receives a Drishti from benefics.",
    Ketu: "If Ketu is in his exaltation, or in his own Ri, or is related to a Yog Karak Grah, or, if Ketu is possessed of positional strength. (It is not laid down anywhere, in which Bhava Ketu does get positional strength).",
  },
  Saturn: {
    Sun: "If Srya is in his exaltation, in his own Ri, or, if Srya is associated with Dharms Lord, or, if Srya is in a Kendr, or Trikon, associated with, or receiving a Drishti from benefics.",
    Moon: "If Candr is full, in her exaltation, or in her own Ri, or in a Kendr, or Trikon, or in the 11th from the Dasha Lord, or, if Candr receives a Drishti from benefics.",
    Mars: "If Mangal is in his exaltation, in his own Ri, or, if Mangal is associated with Lagns Lord, or with the Dasha Lord.",
    Mercury: "If Budh is in a Kendr, or Trikon.",
    Jupiter: "If Guru is in a Kendr, or in a Trikon, or, if Guru is associated with Lagns Lord, or, if Guru is in his own, or in his exaltation Ri.",
    Venus: "If ukr is in a Kendr, Trikon, or in Labh, associated with, or receiving a Drishti from benefics. If during the period of Antar Dasha of ukr Guru is favourable in transit, there will be dawn of fortune and growth of property.",
    Saturn: "If ani is in his own, in his exaltation Ri, or in deep exaltation, or, if ani is in a Kendr, or Trikon, or, if ani is a Yog Karak.",
    Rahu: "If Rahu not be in his house of exaltation, or any other auspicious position.",
    Ketu: "Even if Ketu is in his exaltation, in his own, in a benefic Ri, or in a Kendr, or Trikon, or, if Ketu is associated with, or receives a Drishti from benefics. If Ketu is related to the Lagns Lord, there will be gain of wealth and enjoyment and bathing in holy places and visit to a sacred shrine at the commencement of the Antar Dasha.",
  },
  Rahu: {
    Sun: "If Srya is in his exaltation, in his own Ri, in Labh, in a Kendr, or in a Trikon, or in his exalted, or own Nav.",
    Moon: "If Candr is in his exaltation, in his own Ri, in a Kendr, Trikon, or in Labh, or, if Candr is in a friendly Ri, receiving a Drishti from benefics.",
    Mars: "If Mangal is in Labh, Putr, or Dharm, or, if Mangal is in a Kendr, if Mangal receives a Drishti from benefics, or, if Mangal is in his exaltation, or in his own Ri.",
    Mercury: "If Budh is in his exaltation Ri, in a Kendr, or in Putr and, if Budh is endowed with strength. Good results, like Raj Yog, beneficence of the king and gain of wealth and reputation, will be realized particularly on Wednesday in the month of Budh.",
    Jupiter: "If Guru is in his exaltation, in his own Ri, in his own Nav, or in his exalted Nav, or, if Guru is in a Kendr, or in a Trikon with reference to Lagn.",
    Venus: "If ukr is with strength in a Kendr, in a Trikon, or in Labh.",
    Saturn: "If ani is in a Kendr, in a Trikon, in his exaltation, in his own Ri, in his Multrikon, in Sahaj, or in Labh.",
    Rahu: "If Rahu is in Kark, Vrischik, Kanya, or Dhanu and is in Sahaj, Ari, Karm, or Labh, or is yuti with a Yog Karak Grah in his exaltation Ri.",
    Ketu: "There will be journeys to foreign countries, danger from the king, rheumatic fever etc. and loss of cattle.",
  },
  Ketu: {
    Moon: "If Candr is in her exaltation, in her own Ri, in a Kendr, Trikon, in Labh, or in Dhan. The beneficial results will be realized fully, if Candr is waxing.",
    Mars: "If Mangal is in his exaltation, in his own Ri, if Mangal is associated with, or, receives a Drishti from benefics. If Mangal is related to Dharms, or Karms Lord, there will definitely be gain of land and enjoyment.",
    Mercury: "If Budh is in a Kendr, or Trikon, or, if Budh is in his exaltation, or in his own Ri.",
    Jupiter: "If Guru is in his exaltation, in his own Ri, or is associated with Lagns, Dharms, or Karms Lord in a Kendr, or Trikon.",
    Venus: "If ukr is in his exaltation, in his own Ri, or, if ukr is associated with Karms Lord in a Kendr, or Trikon and there will be dawn of fortune, if in such position he is associated with Dharms Lord also.",
    Saturn: "If ani is deprived of strength and dignity. There will be loss of wealth and lethargy, if ani is in Randhr, or Vyaya.",
    Rahu: "If Rahu is in his exaltation, his own, in a friends Ri, or in a Kendr, or Trikon, or in Labh, or Sahaj, or Dhan. There will be some trouble at the commencement of the Dasha, but all will be well later.",
  },
};
