// Horā Sāra (Pṛthuyaśas) planet-in-HOUSE effects (Ch. 21), corroborating Bhṛgu
// & Sārāvalī. Auto-extracted; Sanskrit graha/bhāva names normalised on parse.
import type { PlanetName } from "./constants";

export const HORASARA_HOUSE: Partial<Record<PlanetName, Record<number, string>>> = {
  Sun: {
    1: "One born at the time of sunrise (Sūrya in Lagn) will not be quiet and calm, neither will he have many sons. He will be unkind, be fond of war and weak-sighted, he will speak less, will live in foreign countries and be happy.",
    2: "The native with Sūrya in Dhan Bhava will have facial diseases. He will be wealthy and he will incur royal wrath and have fear of theft.",
    3: "In Sahaj Sūrya makes one irascible and strong. Such a natives death occurs among his relatives. He will be famous.",
    4: "One, who has Sūrya in Bandhu Bhava will not have money of his own, will be distressed, wise and valorous.",
    5: "The one, who has Sūrya in Putr Bhava will be a fast speaker, will have sharp memory, few sons and be not wealthy.",
    6: "When Sūrya is posited in Ari Bhava, one will be a kings minister, a leader, be learned and famous.",
    7: "Should Sūrya be in Yuvati, one will be playful, be not attached to his wife and will have an unquiet disposition.",
    8: "Should Sūrya be in Randhr Bhava, ones eye sight will be maimed. There will not be many children. Sickness and fame will be both present in the life of the native.",
    9: "Sūrya in Dharm Bhava will make one virtuous. The native will have wife and sons and will dislike his father.",
    10: "The person, who has Sūrya in Karm Bhava will attend to royal duties at all times; he will be brave and like warring. He will be widely famous.",
    11: "One with Sūrya in Labh will become very rich, will have amicable servants and be dear to the king.",
    12: "Should Sūrya be in Vyaya Bhava one will not have money, be disabled, afflicted and one will be in other countries. Sūrya in debilitation Amsh and in inimical Amsh will increase the affliction to the Bhava concerned.",
  },
  Moon: {
    1: "Should Candr be in Mesh, Vrishabh, or Kark, as Lagn, the native will be wealthy, happy and equal to a king. In other Rāśis identical with Lagn Candr does not give speech, wisdom, wealth and strength.",
    2: "Should Candr be in Dhan, one will be courageous, rich and dear to women and one will be happy with little.",
    3: "In Sahaj Candr will give calumniating tendency, kindleness and cunningness.",
    4: "If Candr is in Bandhu, one will have sweet food, be modest, addicted to women and be happy.",
    5: "Should Candr be in Putr, one will possess wife, wisdom and strength, his wealth will be hard-earned.",
    6: "The native, who has Candr in Ari Bhava will be idle and poor and will have many foes. He will curb, or overpower his co-borns.",
    7: "Should Candr be in Yuvati, the native will be close to his wife, be a leading person in the kings employ and will be liberal.",
    8: "Should Candr be in Randhr, one will be wealthy, will enjoy luxuries, will be wise and very courageous.",
    9: "In Dharm Candr will make one virtuous, talkative, go after women and preside over money (wealthy).",
    10: "The native, who has Candr in Karm Bhava will gather money by all (fair) means. He will have an artful and clever wife.",
    11: "Should Candr be in Labh, one will be rich and a good scholar. He will possess cows, be acceptable to the king and be modest.",
    12: "One who has Candr in Vyaya will have afflicted eyes, defective limb, sufferings from women and he will be fickle-minded. If Candr is in Vyaya in own Rāśi, or in exaltation, or she is waxing, though in Vyaya, happiness and wealth will follow.",
  },
  Mars: {
    1: "One having Mangal in Lagn will have an injured limb, be brave and strong. He will be respected and mighty. He will also be fickle-minded, short-lived, wild, idle and be troubled by bilious diseases.",
    2: "The native, who has Mangal in Dhan, will have high incidence of expenses, a limb crippled and be harsh in speech.",
    3: "Mangal in Sahaj will make one dislike his co-born and earn money with difficulty, he will become rich and be lucky.",
    4: "Mangal in Bandhu will make one desirous of living in others houses, will make one sick and wealthy.",
    5: "In Putr it makes a person grieved, ill-natured and quite intelligent.",
    6: "Should Mangal be in Ari Bhava, one will be base and idle.",
    7: "If Mangal is posited in Yuvati Bhava, the native will subdue to his wife and live in foreign countries.",
    8: "In Randhr Bhava Mangal will make ones existence difficult. The person will be forsaken by his wife and sons.",
    9: "Should Mangal be in Dharm, one will indulge in killing the people on the way.",
    10: "If Mangal is placed in Karm, the subject will become dear to the public and be highly intelligent.",
    11: "If Mangal is posited in Labh, the native will have excellent qualities.",
    12: "If Mangal is placed in Vyaya, the native will be a befallen person and be disabled.",
  },
  Mercury: {
    1: "Budh in Lagn will make one learned, wealthy and kind.",
    2: "In Dhan Budh makes one rich and lucky.",
    3: "Should Budh be in Sahaj, the subject will become rich on account of his own good qualities.",
    4: "In Bandhu he will be scholarly and learned.",
    5: "Budh in Putr makes one very intelligent, sweet in speech, wise and accepted even by scholars.",
    6: "If Budh is placed in Ari Bhava, the native will be of argumentative nature, will hate the public and live in foreign countries.",
    7: "One who has Budh in Yuvati will be a Mimamsaka, knowing the right and wrong course of action, be liberal-minded and widely famous.",
    8: "In Randhr Budh makes one famous, Lord of money, king and wise.",
    9: "Should Budh be in Dharm Bhava, one will be very brave, will possess wealth and corn and be very enthusiastic.",
    10: "With Budh in Karm one will become Lord of money, give donations, be intelligent and famous.",
    11: "Should Budh be in Labh Bhava, the native will earn in several (fair) ways and be rich, be dear to women and of good qualities.",
    12: "If Budh is placed in Vyaya, one will be cruel, unkind and will be a spendthrift.",
  },
  Jupiter: {
    1: "If Guru is placed in Lagn, the native will be long lived, wise and happy. This does not apply, if the Grah is in fall.",
    2: "In Dhan Bhava, Guru makes one wealthy, a good speaker, kind and interested in worshipping the Gods.",
    3: "Guru in Sahaj Bhava will give bad disposition, but no wealth. The person will be ominous to his co-born and relatives.",
    4: "In Bandhu Bhava, Guru makes one happy and gives a good wife. The subject will have good food, residence, conveyances etc.",
    5: "Guru in Putr Bhava will give a good wife and sons. He will be fortunate, a scholar and an able speaker.",
    6: "In Ari Bhava, Guru will give no enemies, make him a minister of the king and prudent.",
    7: "Guru in Yuvati will bless one with a good wife and sons and will make him a better scholar than ever before.",
    8: "In Randhr Guru contributes to long lease of life. The native will become a king, be learned and have his force of enemies destroyed.",
    9: "Guru in Dharm will make one enjoy all kinds of happiness. The native will be learned, splendorous, virtuous and wealthy.",
    10: "In Karm Bhava, Guru will bestow wide fame, engagement in good acts and make one very wealthy.",
    11: "When Guru is placed in Labh, the person will have gains from various sources, will become head of a treasury, principal member of his clan and be well-versed.",
    12: "In Vyaya Guru makes a person defective-limbed and spend money in charity and dances.",
  },
  Venus: {
    1: "Śukr in Lagn gives such beauty equal to Manmadha and also qualities. The person will be won by women, be wealthy and versed.",
    2: "When Śukr is placed in Dhan Bhava, one will be conscientious, have cheerful face and be kind.",
    3: "One will join base women for the sake of sensual pleasures, if Śukr is placed in Sahaj. He will not have wealth and luxuries.",
    4: "If Śukr is placed in Bandhu, one will be happy and will tend to pardon others. He will be kind and have wife and sons.",
    5: "Should Śukr be in Putr, one will be a kings minister, or a leader, he will have female issues and be learned.",
    6: "In Ari Śukr makes one be without enemies, be of cunning disposition and be sickly, he will also lose his wealth and sons.",
    7: "Should Śukr be in Yuvati Bhava, the person will be infatuated with passion, will hate his friends and will be close to chief persons.",
    8: "If Śukr is placed in Randhr, one will be of varied nature, sick, will have wife and children and one will be delighted.",
    9: "Should Śukr be strong in Dharm, one will possess wisdom, virtues, luxuries, wife and sons.",
    10: "In Karm Bhava, Śukr will make one dear to women, become a kings minister and will dig wells, tanks etc. for the public.",
    11: "Śukr in Labh Bhava gives superior knowledge, wealth, kindness, gains and satisfaction.",
    12: "If Śukr is placed in Vyaya Bhava, it makes a person go after women, otherwise righteous, but undutiful.",
  },
  Saturn: {
    1: "Should Śani be in Lagn, the native will be very sick in his boyhood, be dirty and a wanderer. He will also be wicked in nature. He will not be loyal to the fair sex and he will be windy in temperament; he will be disabled.",
    2: "If Śani occupies Dhan Bhava, the native will not have any money left by his father. He will have self respect, courage, wealth and be learned.",
    3: "If Śani is placed in Sahaj Bhava, one will be brave, unkind, witty and disrespected.",
    4: "If Śani is in Bandhu Bhava, one will be troubled by his own relatives, will not have many sons and will be unhappy.",
    5: "If Śani is posited in Putr Bhava, the native will be dull, will have limited number of sons and will suffer from eye diseases. He will be a wanderer.",
    6: "If Śani is in Ari Bhava, the native will be helpful, be free from any enemies and diseases and he will be very famous.",
    7: "Should Śani be in Yuvati Bhava, one will be mean, fickleminded, grieved and one will be fond of his wife though she will be wicked.",
    8: "If Śani is in Randhr Bhava, one will be wealthy, sick, will not have many sons, will be weak sighted and fickleminded.",
    9: "If Śani is placed in Dharm Bhava, one will hold the flag of Dharma aloft, be a great expert, be greatly wise and just and one will have sons.",
    10: "Should Śani be posited in Karm Bhava, one will have good mental disposition, will be wealthy, chief of his caste and happy.",
    11: "If Śani is placed in Labh Bhava, the native will be of lordly disposition and famous; he will be a scientist and an expert in the use of weapons (and in surgery).",
    12: "If Śani is in Vyaya Bhava, the native will blame others, be burdened with heavy expenditure and be unhappy.",
  },
};
