// Sārāvalī planet-in-HOUSE effects (Ch. 30), corroborating Bhṛgu. Auto-extracted.
import type { PlanetName } from "./constants";

export const SARAVALI_HOUSE: Partial<Record<PlanetName, Record<number, string>>> = {
  Sun: {
    1: "The Sun in the Ascendant denotes, that the native will have less hair (on the head), be lazy in function, given to anger, will have prominent personality, be honourable, will have weak sight and coarse physique, be courageous, impatient and unkind. If the Ascendant is Cancer and is occupied by the Sun, the native will have swollen eyes, if it be Aries with Sun therein, his sight will be weak and in Leo the Sun makes him night -blind. One suffers poverty and loss of children, if the Sun occupies Libra.",
    2: "SUN IN 2nd. If the Sun is in the 2nd Bhava, the native will be endowed with servants and quadrupeds, will suffer facial diseases, will be deprived of happiness and wealth and will lose money through royal displeasure, or through thieves.",
    3: "Should the Sun be in 3rd, the native will be valorous, strong, will lose co-born, be dear to people, good- looking, very learned and will conquer his enemies.",
    4: "Should the Sun be in 4th, the native will be devoid of conveyances and relatives, will suffer heart diseases, will destroy paternal house and wealth and will serve a bad king.",
    5: "If the Sun occupies the 5th, the native will be bereft of happiness, sons and wealth, will live by husbandry, will move in hills and fortresses, be fickle-minded, scholarly, devoid of strength and be short-lived.",
    6: "If the Sun is in 6th, the native will be very libidinous, will have powerful digestive fire (capable of digesting fast), be strong, affluent, famous for virtues and be either a king, or an Army chief.",
    7: "If the Sun is posited in 7th, the native will be poor, insulted, will suffer bodily diseases, royal displeasures and imprisonment, will take to bad ways and will not be well-disposed to his wife.",
    8: "If the Sun occupies the 8th, the native will have deformed eyes, be devoid of wealth and happiness, be short-lived and will suffer separation from his relatives.",
    9: "If the Sun occupies the 9th, the native will be endowed with wealth, children and friends, will be very interested in worshipping Gods and Brahmins, will not be well-disposed towards his father and wife and be not calm.",
    10: "Should the Sun be in 10th, the native will be extremely intelligent, rich, strong and will be endowed with conveyances, relatives and sons, will succeed in his undertakings, be valorous, unconquerable and great.",
    11: "Should the Sun be in 11th, one will be interested in gathering money, be strong, will hate others, be devoid of servants, be himself a servant, be devoid of affection, be modest and will be successful in undertakings.",
    12: "If the Sun is in 12th at birth, he will have a deformed physique, be one-eyed, fallen (morally), will marry a barren lady, be inimical to his father, weak and mean.",
  },
  Moon: {
    1: "The Moon in the Ascendant identical with Cancer, Taurus, or Aries indicates, that the native will be liberal, beautiful, rich and enjoying pleasures greatly. The Moon in the Ascendant identical with other Signs indicates, that the native will be intensely passionate, base, deaf, distressed, dumb and will decline (in prosperity).",
    2: "Should the Moon be in 2nd, the native will enjoy incomparable happiness and friends and be wealthy. If the said Moon be Full, the native will be very affluent and will speak less.",
    3: "Should the Moon be in 3rd, the native will protect his co-born, be always delighted, valorous and will be endowed with learning, robes and food.",
    4: "If the Moon be in 4th, the native will be endowed with relatives, paraphernalia and conveyances, be charitable, fond of travelling by water and will neither be very happy nor be miserable.",
    5: "Should the Moon be in 5th, the native will be timid in disposition, will earn learning, clothes and food, will have many sons and friends, be a scholar and be passionate.",
    6: "If the Moon be in 6th, the native will suffer stomachial diseases. If it be the weak Moon, he will be short-lived.",
    7: "If the Moon is in 7th, the native will be amiable, happy, will possess a good physique and be sensuously disposed. If the weak Moon is in 7th, the native will be pitiable and weak.",
    8: "If the Moon is in 8th, the native will be very intelligent, very splendourous and will suffer from diseases. If the Moon be weak, he will be short-lived.",
    9: "If the Moon is in 9th, the native will be devoted to divine and paternal assignments, will be endowed with happiness, wealth, intelligence and sons and will attract the fair sex.",
    10: "If the Moon occupies the 10th, the native will not suffer grief, be dutiful, successful in his undertakings, affluent, pure, very strong, valorous and charitable.",
    11: "Should the Moon occupy the 11th, the native will be wealthy, will have many sons, be long- lived, will have attendants to serve, be intelligent, sharp, valorous and splendourous.",
    12: "If the Moon occupies the 12th, the native will be odious, fallen in moral sense, mean, will suffer eye diseases, be indolent, distressed (deformed), is born of others loins and will be insulted at all times.",
  },
  Mars: {
    1: "If Mars occupies the Ascendant, the native will be cruel, adventurous, dull-witted, short-lived, honourable, courageous, will have an injured physique, be attractive in appearance and fickle-minded.",
    2: "If Mars occupies the 2nd, the native will be poor, will eat bad food, will possess an ugly face, will join bad men and be bereft of learning.",
    3: "If Mars be in 3rd, the native will be courageous, unconquerable, bereft of co-born, be delighted, will have all virtues and be famous.",
    4: "If Mars is posited in 4th, the native will be devoid of relatives, paraphernalia and conveyances, be very miserable, will live in others houses and be distressed.",
    5: "If Mars occupies the 5th, the native will be devoid of happiness, wealth and sons, be fickle- minded, be a talebearer, will incur evils, be wicked, distressed and mean.",
    6: "If Mars occupies the 6th, the native will be highly libidinous, will have powerful digestive fire, be beautiful, tall, strong and great among his relatives.",
    7: "If Mars is posited in 7th, the native will lose his wife, will suffer from diseases, will take to bad ways, be miserable, sinful, devoid of wealth, distressed and emaciated.",
    8: "If Mars occupies the 8th, the native will suffer from diseases, be short-lived, will possess an ugly, or deformed body, will do base acts and will suffer grief.",
    9: "If Mars occupies the 9th, the native will not be skillful in acts, be odious, will kill living beings, be not virtuous, be very sinful and honoured by the king.",
    10: "If Mars occupies the 10th, the native will be proficient in his acts, be valorous, unconquerable, will serve important people, be endowed with sons and happiness and be very courageous.",
    11: "If Mars occupies the 11th, the native will be virtuous, happy, courageous, endowed with wealth, grains and sons and be devoid of sorrow.",
    12: "Should Mars be in 12th, the native will have diseased eyes, will fall in moral sense, will kill his wife, be a talebearer, be fierce and will contract humility and imprisonment.",
  },
  Mercury: {
    1: "Should Mercury occupy the Ascendant, the native will have a flawless physique, be intelligent, will know proper(beneficial) place and time, be well-versed in poetry and mathematics, be a skillful and sweet speaker and be long-lived.",
    2: "If Mercury is in the 2nd, the native will earn wealth through his own wisdom, will enjoy food and drinks, be auspicious in speech and will have good course of conduct.",
    4: "If Mercury is in 4th, the native will be endowed with money and relatives, be fortunate, will have conve yances, all paraphernalia and relatives and be very learned.",
    5: "If Mercury occupies the 5th, the native will be an expert in Mantras (sacred spells) and Abhicara (malevolent spells), will have many sons, be endowed with learning, happiness and efficacy and be delighted.",
    6: "If Mercury occupies the 6th, the native will always be successful in litigations and disputes, will contract diseases, be indolent, not given to anger, be harsh in speech and much insulted.",
    7: "If Mercury is in 7th, the natives wife will be very learned, beautiful in appearance, will not be of good descent, will promote quarrels and be very affluent. The native himself will be very great.",
    8: "If Mercury occupies the 8th, the native will win famous names (titles), be strong, long- lived, will support his family and be equal to a king, or will become a justice.",
    9: "If Mercury occupies the 9th, the native will be very affluent, scholarly, of good conduct/habits, be eloquent in speech, skilful of a great order and be virtuous.",
    10: "If Mercury occupies the 10th, the native will possess distinguished intelligence, will perform distinguished acts, will attain fruition in undertakings, be very learned, courageous, strong and will be endowed with various kinds of ornaments.",
    11: "If Mercury occupies the 11th, the native will be rich, be an amicable worker, be learned, happy and endowed with wide enjoyments, be long-lived and famous.",
    12: "Should Mercury be in the 12th, the native will be able to keep up his promise, be indolent, be humiliated, be a good speaker, be learned, pitiable and cruel.",
  },
  Jupiter: {
    1: "If Jupiter occupies the 1st, the native will be attractive in appearance, energetic, long- lived, will act after assessing consequences, be learned, courageous and great.",
    2: "Jupiter in the 2nd. If Jupiter occupies the 2nd, the native will be rich, will enjoy good food, be an eloquent speaker, be fortunate, be charitable and will have a beautiful body and face.",
    3: "If Jupiter occupies the 3rd, the native will be greatly humiliated, be vile, ever successful, will have digestive deficiencies, be defeated by women and be sinful in acts.",
    4: "If Jupiter occupies the 4th, the native will be endowed with relatives, paraphernalia, conveyance, happiness, intelligence, pleasures and wealth, be great and be a source of misery to his enemies.",
    5: "If Jupiter occupies the 5th, the native will have abundant happiness, many sons and friends, be learned, courageous, wealthy and will always be happy.",
    6: "If Jupiter is in the 6th, the native will lack digestive fire and masculine virile, be humiliated, weak, indolent, will become famous on account of females, will destroy his enemies and be widely famous.",
    7: "If Jupiter occupies the 7th, the native will be charming, will acquire a beautiful wife, be greater than his father, be an eloquent speaker, a poet, a superior person and be learned and famous.",
    8: "If Jupiter occupies the 8th, the native will be insulted, long-lived, be a servant, will serve his own people, be pitiable and will have union with dirty women.",
    9: "If Jupiter is in 9th, the native will be attached to divine and paternal duties, be learned, fortunate, be a kings minister, or a leader and be chief.",
    10: "If Jupiter occupies the 10th, the native will attain successful beginning in his undertaking, be honourable, effortful and will be endowed with abundant welfare, happiness, wealth, relatives, conveyances and fame.",
    11: "If Jupiter occupies the 11th, the native will enjoy many gains, many conveyances and many servants, be virtuous, but will have limited education and few sons.",
    12: "If Jupiter occupies the 12th, the native will be indolent, odious, be devoid of speech and luck and will be in all probability in servitude.",
  },
  Venus: {
    1: "If Venus is in Ascendant, the native will possess beautiful eyes, face and physique, be happy, long-lived, timid and attractive to females.",
    2: "If Venus is in the 2nd, the native will enjoy abundant food, drinks and wealth, will derive excellent pleasures, be endowed with good speech and will amass great wealth.",
    3: "If Venus occupies the 3rd, the native will be happy, rich, conquered by women, be vile, little enthusiastic and will be bereft of luck and paraphernalia.",
    4: "If Venus occupies the 4th, the native will be endowed with relatives, friends and happiness, be splendourous, will have conveyances and paraphernalia, be beautiful, rich and fortunate.",
    5: "If Venus is posited in the 5th, the native will be endowed with happiness, sons and friends, be fond of sexual union, be very affluent, full of everything and be a minister, or a justice.",
    6: "If Venus occupies the 6th, the native will greatly dislike his wife, will have many foes, be devoid of wealth, be very much startled and be mean.",
    7: "If Venus occupies the 7th, the native will be very beautiful, be happy with his wife, will enjoy great riches, be devoid of quarrels and be fortunate.",
    8: "If Venus is in the 8th, the native will be long-lived, will enjoy incomparable happiness, be very rich, be equal to a king and moment after moment will feel delighted.",
    9: "If Venus occupies the 9th, the native will possess a spotless and broad physique, be endowed with wealth, charitable, wife, sexual pleasures and friendship and will honour Gods, guests and preceptors/elders.",
    10: "Should Venus occupy the 10th, the native will earn success in litigations and will be endowed with happiness, sexual unions, honour, wealth, fame and great wisdom.",
    11: "If Venus is positioned in 11th, the native will have obedient servants, be bereft of all kinds of misery and will gain abundantly.",
    12: "Should Venus be in 12th, the native will be indolent, happy, corpulent, fallen in moral sense, will eat cleansed food, will be skilful in providing sleeping comforts and attendants and will be won over by women.",
  },
  Saturn: {
    1: "If Saturn happens to be in the Ascendant identical with exaltation, or own House, the native will equal a king in status, or will head a country, or city. If Saturn is in the Ascendant in other Rasis, then his own, or exaltation Rasi, the planet will give misery in boyhood, dirty disposition and indolence.",
    2: "If Saturn occupies the 2nd, the native will have an ugly face, will enjoy worldly prosperity, be devoid of his own men, will render justice, will later on (in the course of his life) go to other countries and will earn money and conveyances.",
    3: "If Saturn occupies the 3rd, the native will be dark in complexion, will maintain physical cleanliness, be base, will have indolent attendants, be courageous, charitable and will have great intelligence.",
    4: "SATURN IN THE 4th. If Saturn occupies the 4th Bhava, the native will suffer heart disease, or be broken-hearted, be devoid of relatives, conveyances, wealth, intelligence and happiness, will suffer sickness in boyhood and will have (prominent) nails and hair.",
    5: "SATURN IN THE 5th. Should Saturn occupy the 5th Bhava, the native will be bereft of happiness, sons, friends, intelligence and kindness, be agitated and be poor.",
    6: "If Saturn occupies the 6th, the native will be very licentious, be beautiful, courageous, will eat abundantly, be crooked and will conquer many of his enemies.",
    7: "If Saturn is posited in the 7th, the native will always be subjected to ill health, will lose his wife, be bereft of wealth, will present himself ugly, be sinful and will do very mean acts.",
    8: "If Saturn occupies the 8th, the native will suffer from leprosy and fistula in the anus, or pudendum, will have short life and will fail in his undertakings.",
    9: "If Saturn occupies the 9th, the native will be devoid of religious merits, will not have much wealth, be bereft of co-born, sons and happiness and will cause sorrow to others.",
    11: "If Saturn occupies the 11th, the native will be long-lived, endowed with lasting riche s, be courageous, will have knowledge of arts, be devoid of sickness and be endowed with money, people and wealth.",
    12: "If Saturn occupies the 12th, the native will be distressed, fallen in moral sense, talkative, will have defective eyesight, be unkind, shameless, will spend much and be insulted.",
  },
};
