// Saravali — planet-in-sign results (auto-extracted). SARAVALI_SIGN[planet][signIndex].
// Source: Kalyana Varma's Saravali. For the interpretation engine.

import type { PlanetName } from "./constants";

export const SARAVALI_SIGN: Partial<Record<PlanetName, Record<number, string>>> = {
  "Sun": {
    "0": "One, who has the Sun in Aries will comment on the meanings of Shastras, be famous in arts, fond of war, fierce, attached to his duty, fond of roaming, will have strong bones, be good in deeds, will do valorous acts, will be subjected to bilious and bloody disorders, be splendourous and strong. The native will also become a king.",
    "2": "IN ASPECT TO OTHERS. Should the Sun be in Gemini, or Virgo be aspected by the Moon, the native will be put to troubles by enemies and relatives, will be distressed by visits to foreign countries. and will in general be wailing. The Sun in a House of Mercury and in aspect to Mars denotes, that the subject will have fear from enemies, will be encountered by quarrels, will be grieved on account of loss in a war, be poor and bashful. Should Mercury aspect the Sun posited in Gemini, or Virgo, the subject will have a history akin to that of a king, will be famous, be endowed with relatives, free fro",
    "8": "/PISCES AND ASPECTED BY OTHERS. Should the Sun at birth be in a f Jupiter, the subject will earn fame through battle, be endowed with clarity of speech, money and happiness and be short-tempered. Mercury aspecting the said Sun denotes, that the native will possess sweet speech and will have knowledge of writing, literature, arts, assembly, Journey and minerals. If Jupiter aspects the Sun in Pisces/Sagittarius, the person will move in royal palaces, or be a king himself, will possess elephants, horses and wealth and be ever after learning. Should Venus aspect the Sun in Jupiter's House, one wil",
    "10": "If the Sun is in Aquarius at birth, one will suffer from heart diseases, will have enormous strength (courage), be very short-tempered, be fortunate through other housewives, be hated by the learned, be firm in his activities, be miserable, will have little wealth, be fraudulent, be not firm in friendship, will have dirty body and be a miser. 66-67. If the Sun is in Pisces at birth, one will be friendly, will have tendency to amass, be fond of women and happy, be learned, will destroy many enemies and be wealthy and rich. He will be endowed with wife, good sons and servants, will have wealth o"
  },
  "Moon": {
    "0": "IN ASPECT TO OTHERS. If the Moon is in Aries at birth and be in aspect to the Sun, the native will be quite irascible, be honoured by the king, be soft, be valorous and fond of war. If the Moon in Aries is aspected by Mars, the person will suffer from diseases of eyes and teeth, will have wounds caused by arrows (or horse/cow etc.) and will suffer windy diseases and urinary disorders. Should Mercury aspect the Moon in Aries, the native will teach various disciplines, will possess good speech, will achieve his desires, be a great poet and be widely famous. If Jupiter aspects the Moon in Aries,",
    "3": "IN ASPECT TO OTHERS. Should the Moon be in her House at birth and be aspected by the Sun, the native will be in the employ of king, be not rich, be a letter-bearer and will protect forts (i.e. will be a security officer in royal service). If the Moon in Cancer is aspected by Mars, the subject will be valorous, be deformed, will prove ominous to his mother and be skillful in his jobs. Should Mercury lend his aspect to the Moon in Cancer, he will be spirited in disposition, be endowed with political wisdom, wealth, wife and sons, will be a kings minister and be happy. Jupiter aspecting the Moon",
    "6": "IN ASPECT TO OTHERS. If the Moon is in Libra and is aspected by the Sun, the person will be bereft of wealth, be diseased, will wander here and there, be insulted, be bereft of enjoyment, sons and strength. If Mars aspects the Moon in Libra, the person will be sharp, be a thief, be mean, adulterous, will enjoy scents and garlands, be wise and will suffer from eye diseases. If Mercury aspects the Moon in Libra, the subject will be skillful in arts, will have abundant riches and grains, will be an auspicious speaker, be highly learned and be famous in his country. Should Jupiter aspect the Moon",
    "7": "IN ASPECT TO OTHERS. If the Moon at birth is in Scorpio and aspected by the Sun, the native will hate people (i.e. will not be friendly with others), be learned, wandering nature and rich, but be not happy. Should Mars aspect the Moon in Scorpio, the native will have incomparable courage, be equal to a king, be endowed with wealth, be valorous, unconquerable in battle and be a voracious eater. If Mercury aspects the Moon in Scorpio, the person will not be skillful, be hard in speech, will obtain twins, be tricky, will produce fictitious things and be an expert singer. If Jupiter lends aspect t",
    "9": "If the Moon at birth be in Capricorn, the native will be a singer, will be averse to cold articles (or season), will have stout body, will be fond of truth and charity, be distinguished, famous, less irascible, be libidinous, unkind and shameless; will possess beautiful eyes and emaciated body, will violate teacher's bed, be a poet, will have round thighs, be not very enthusiastic, be very miserly and will have long neck and ears. 66-71.",
    "11": "If the Moon is in Pisces, the native will be expert in fine arts, be capable of winning even unfavourable people, be learned in Shastras, beautiful bodied, proficient in music, very religious, will cohabit with many women, be a polite speaker, will serve the king, be somewhat irascible, will have a big head, be endowed with happiness and wealth, will be won over by the fair sex, be virtuous, be interested in sailing and be liberal. 80-85."
  },
  "Mars": {
    "2": "Should Mars be in Gemini, the native will be splendourous, be capable of enduring miseries, be very learned, be well versed with poetical rules, skillful in various kinds of fine arts, fond of going to foreign countries, virtuously disposed, highly intelligent, favourably disposed to his sons and friends and will devote to various kinds of assignments. 7-8.",
    "3": "If Mars is in Cancer at birth, the subject will like living in others' houses, be deformed, sick, will attain riches through agriculture, will enjoy royal food and robes during childhood, will eat food in others' houses, will become wealthy through the source of water, be repeatedly anguished and be always distressed. 9-10.",
    "4": "If Mars is in Leo in a nativity, the native will be impatient, be valorous, intent upon grabbing others' money and children, will like to live in forests, be fond of eating cow's flesh (or beef etc.), will lose his first wife, will kill snakes and animals, will be bereft of children, be devoid of charitable acts and be always active in his jobs. 11-12.",
    "5": "Should Mars occupy Virgo at birth, the subject will be worthy of honour, be never rich, be very fond of sexual union and music, be soft and sweet spoken, will have various kinds of expenses, be not much valorous, be learned, will have ribs in their advanced position, will fear enemies very much, be skillful in Shastras and fine arts, be fond of bathing, make-up etc. and be splendourous. 13-14. If Mars occupies Libra in a nativity, the person will be liable to wandering, will indulge in bad business, be an able speaker, be fortunate, deformed in respect of some limb, will have few relatives, be",
    "7": "If Mars occupies Scorpio at birth, the native will be attached to trade, will be interested in Vedic knowledge, be leader of thieves, skillful in his duties, be interested in wars, be highly sinful, will do big crimes, will be perfidious towards his enemies, will betray, be disposed towards killing, be unhelpful, be a talebearer, will be endowed with lands, sons and wife and be troubled by poison, fire, weapons and wounds. 17-18.",
    "8": "Should Mars be in Sagittarius, the native will have many wounds, be emaciated, be harsh in speech, crafty, alienated, be a warrior endowed with chariots, elephants and Army men, will pass arrows on other's Army from his chariot, be happy with hard work, will lose his happiness and money due to anger and will not honour elders. 19-20. If Mars is posited in Capricorn at birth, one will be wealthy (fortunate), be endowed with happiness and pleasures, be wealthy, will have an excellent disposition, be famous, be an Army chief, or a king, will possess a good wife, be successful in war, will live in",
    "11": "Should Mars be in Pisces at the time of one's birth, the person will be troubled by diseases, will have indifferent children, will live in foreign countries, be insulted by his own relatives, will lose all his wealth by his cunning and cheating disposition, will be depressed in spirits, be very miserable, will disrespect elders and Brahmins, be unkind, will conceive (other's) desires, be fond of praises and be famous."
  },
  "Mercury": {
    "1": "/LIBRA IN ASPECT TO OTHERS. Should Mercury be in a House of Venus and be aspected by the Sun, the subject will suffer from penury and acute grief, will have a sick physique, be interested in serving others and will be censured. Should Mercury be in a House of Venus and be aspected by the Moon, the native will be trustworthy, affluent, firmly pious, devoid of sickness, will have lasting family ties, be famous and be a kings minister. Should Mercury be in a House of Venus and be aspected by Mars, the native will be troubled by diseases and enemies, be distressed, will incur royal insult and will",
    "3": "IN ASPECT TO OTHERS. Should Mercury be in Cancer, in aspect to the Sun, one will be a dhoby, or a gardener, or a house-builder, or gem smith. If the Moon aspects Mercury in Cancer, one will be deprived of wealth (or energy of the physique) on account of women and will be miserable for the same reason. If Mars lends his aspect to Mercury in Cancer, he will not have much learning, be garrulous, be a great liar, will produce fictitious things, be a thief and will be affectionate in speech. If Jupiter aspects Mercury in Cancer, one will be a great scholar, very dear (to all), be fortunate, dear to",
    "4": "IN ASPECT TO OTHERS. If Mercury occupies Leo at birth and is aspected by the Sun, the native will be jealous, rich, virtuous, cruel, mean, fickle-minded and shameless. If the Moon aspects Mercury in Leo, one will be very beautiful, very skillful, be interested in poetry, fine arts, music and dance, be wealthy and virtuous. If Mars lends his aspect to Mercury in Leo, one will be base, miserable, physically injured, unskillful and impotent. If Jupiter aspects Mercury in Leo, one will be beautiful, very learned, be a gifted speaker, be very famous and be endowed with attendants and conveyances. I",
    "7": "If Mercury is posited in Scorpio, one will experience troubles, grief and evils, will hate the virtuous, will be devoid of truth, religion and shame, be a dunce, be not virtuous, be a miser, will cohabit with wicked women, be fond of giving cruel punishments, be not out spoken, be interested in blameworthy jobs, will incur debts, will join base men and will steel other's properties. 17-18. Should Mercury be in Sagittarius, the native will be famous, liberal, will have knowledge of Vedas and writing and fine arts. 19-20.",
    "9": "If Mercury is in Capricorn at birth, the native will be mean, dull, impotent, will do others' work, be devoid of virtues, be subjected to various kinds of miseries, will dream, wander etc., be a tale bearer, be untruthful, devoid of relatives, dirty and timid. 21-22.",
    "10": "Should Mercury be in Aquarius at birth, the subject will be bereft of good disposition and good deeds, be attached to many religious acts, will give up doing worthy things, be insulted by others, be impure, be not virtuous, be very wicked, be inimical to wife, be devoid of carnal pleasures, be very unfortunate, very timid, impotent, dirty and modest. 23-24. Should Mercury be in Pisces, one will be fond of good conduct and purity, will live in foreign countries, be issueless, poor, will have a chaste wife, be virtuous, fortunate, be devoid of religion, be skillful in stitching etc. and be devoi"
  },
  "Jupiter": {
    "0": "If Jupiter is posited in Aries at birth, one will be argumentative in disposition, will acquire precious stones and ornaments out of his efforts, will be endowed with strength, sons and wealth, will have eminent and famous profession, be splendourous, will have many enemies, much expenses and an injured body and will confer fierce and cruel punishments. 3-4. Should Jupiter be in Taurus, one will be endowed with a broad body, be corpulent, will honour Brahmins and Gods, be splendourous, fortunate, attached to his wife, be endowed with good appearance, profession, cows and abundant wealth; will",
    "1": "/LIBRA IN ASPECT TO OTHERS. If Jupiter occupies a House of Venus at birth and is aspected by the Sun, one will be endowed with attendants and quadrupeds. will wander verily, will have a long body, be learned and be a king's minister. If Jupiter occupies a House of Venus and is aspected by the Moon, the native will be abundantly rich, be very calm, Sweet, be dear to mother and wife and will enjoy much pleasures. If Jupiter occupies a House of Venus and is aspected by Mars, the native will be dear to the fair sex, be learned, courageous, affluent, happy and be of royal Scion. If Jupiter occupies",
    "3": "IN ASPECT TO OTHERS. If Jupiter occupies Cancer at birth and is aspected by the Sun, native will be famous, be ahead of others and will (in the beginning) be devoid of happiness, wealth and wife, all of which will be acquired by him later. If Jupiter occupies Gemini/Virgo and is aspected by the Moon, the native will be very rich, splendourous, be a king, will enjoy abundant wealth and conveyances and will have excellent wife and sons. If Jupiter occupies Gemini/Virgo and is aspected by Mars, one will marry in the boyhood itself, will be endowed with gold and ornaments, be learned, valorous and",
    "4": "ASPECTED BY OTHERS. If at birth Jupiter is in Leo and is aspected by the Sun, one will be dear to good men, be famous, be a king, be extremely affluent and virtuous. If Jupiter is in Leo and is aspected by the Moon, the native will be very beautiful, dirty, will be very rich through the fortunes of his wife and will conquer his five senses. If Jupiter is in Leo and is aspected by Mars, the native will honour elders at all times, will perform distinguished acts, be very skillful, pure, adventurous and cruel. If Jupiter is in Leo and is aspected by Mercury, the native will have knowledge of civi",
    "9": "Jupiter in Capricorn denotes, that the native will be less virile, will experience much grief and difficulties, will be mean in conduct, be a dunce, will meet a bad end, will suffer from penury, will serve others, will be bereft of auspiciousness, mercy, purity, affection to his relatives and of religion, will have an emaciated body, be timid, interested in living in other countries and be depressed of spirits. 21-22.",
    "10": "If Jupiter falls in Aquarius at the time of birth, one will be a tale-bearer, be ill disposed, interested in evil jobs, be chief among his racemen, be always attached to base men, be malicious, miserly, will suffer from diseases, will lose wealth on account his own utterances, be devoid of intelligence and virtues and will violate elder's beds. 23-24.",
    "11": "If Jupiter is in Pisces at birth, one will be expert in knowing the meanings of Vedas and other Shastras, will be honoured by friends and virtuous people, will be a headsman in the king's employ, be praiseworthy, unconquerable, rich, devoid of fear, be proud, firm in undertakings, be a king, be skillful in policies, training, behavior and war tactics, be famous and will be calm in his doings."
  },
  "Venus": {
    "0": "OR SCORPIO IN ASPECT TO OTHERS. Should Venus occupy Aries/Scorpio at birth and is in aspect to the Sun, one will be miserable on account of women and will lose wealth and happiness on account of them, will be a king and be learned. If Venus is in Aries, or Scorpio and is aspected by the Moon, one will be imprisoned, very fickle-minded, be libidinous, will marry a base lady and will be bereft of children. If Venus is in Aries, or Scorpio and is aspected by Mars, one will be devoid of wealth, honour and happiness, will do others' jobs and will perform dirty jobs. If Venus is in Aries, or Scorpio",
    "1": "Should Venus at birth be in Taurus, one will be endowed with many wives and gems, be an agriculturist, will possess scents, garlands and robes, will live on account of cows, be charitable, will maintain his relatives, will have good appearance, will be learned in many branches, will give away many things, will help the living beings and be a principal person. 5-6. Sh d Brahmins and be firm in friendship. 7-8. If Venus occupies Cancer at the time of one's birth, he will be wise, virtuous, learned, strong, soft, chief among men, will have desired happiness and wealth, be good-looking, just, very",
    "2": "/VIRGO IN ASPECT TO OTHERS. If Venus is in Gemini/Virgo and aspected by the Sun, one will be well disposed towards the king, his own mother and wife, be learned and rich. If Venus is in Gemini, or Virgo and is aspected by the Moon, one will have dark eyes, beautiful hair, be endowed with sleeping comforts, conveyances etc., be splendourous, beautiful in appearance and be fortunate. If Venus is in Gemini, or Virgo and is aspected by Mars, one will be highly sensuous, be fortunate and will destroy his wealth through women. If Venus is in Gemini, or Virgo and is aspected by Mercury, one will be l",
    "3": "IN ASPECT TO OTHERS. If Venus is in Cancer and aspected by the Sun, the native's wife will be attached to her duties, will possess a spotless body, will be a king's daughter, (i.e. she will be of a rich heritage), one short-tempered and will be endowed with wealth. If Venus is in Cancer and is aspected by the Moon, one will keep his step-mother happy, will have a daughter first and later on many sons, be happy, fortunate and beautiful. If Venus is in Cancer and is aspected by Mars, one will be skillful in arts, be very rich, will suffer on account of women, be fortunate and will promote the ca",
    "4": "IN ASPECT TO OTHERS. If Venus occupies Leo at the time of birth and is aspected by the Sun, one will be jealous, be dear to the fair sex, libidinous will acquire money through women and will possess elephants. If Venus is in Leo and is aspected by the Moon, one will present obsequial water to his step mother, will be miserable on account of women, be rich and will have various kinds of mental disposition (i.e. be infirm in disposition). If Venus is in Leo and is aspected by Mars, one will be a royal person, be famous, dear to women, be affluent, fortunate and be attached to other's wives. If V",
    "6": "If Venus occupies Libra, the native will acquire hard-earned money, be valorous, endowed with superior robes etc., interested in living in foreign countries, will protect his own people, be skillful in his duties, rich, meritorious, famous by honouring Gods and Brahmins, be a scholar and be fortunate. 15-16. If Venus occupies Scorpio, the subject will be jealous, be very malicious, be not religious, be argumentative, be crafty, be not attached to brothers, be not fortunate, will be troubled by enemies, be distressed, will be inimical to unchaste women, be skillful in killing, will incur heavy",
    "8": "/PISCES IN ASPECT TO OTHERS. If Venus occupies Sagittarius/Pisces at birth and aspected by the Sun, one will be very short tempered, learned, wealthy, be liked by all and will go to foreign countries. If Venus is in Sagittarius, or Pisces and is aspected by the Moon, one will be famous, be kingly, will eat rich food, be distinguished and will possess incomparable strength. If Venus is in Sagittarius, or Pisces and is aspected by Mars, one will be very much ill-disposed towards women, will be both happy and miserable, be rich and will possess cows. If Venus is in Sagittarius, or Pisces and is a",
    "9": "If Venus occupies Capricorn at birth, one will be miserable due to heavy expenses, will have an emaciated body, will be fond of aged women, will suffer from heart diseases, be miserly in the matter of money, be a liar, be skillful in cheating, be a eunuch, be devoid of (good) acts, interested in others' work, very distressed, be a dunce and will, however, endure misery. 21-22. Should Venus be in Aquarius, one will suffer from fear and excitement, be not successful in undertakings, will go to other women, be not virtuous, be inimical to elders and to his children, be bereft of ablutions, like b",
    "11": "If Venus is posited in Pisces at birth, one will be courteous, liberal, virtuous, very wealthy, will destroy enemies, be famous in the world, excellent, distinguished, dear to king, be endowed with good speech and wisdom, be liberal, will derive wealth and respect from the virtuous, will keep up his promise, will maintain his family members and be endowed with knowledge. 25-30."
  },
  "Saturn": {
    "0": "/SCORPIO IN ASPECT TO OTHERS. If Saturn occupies a inded, base, will join mean and ugly women and be devoid of happiness and wealth. If Saturn is in Aries, or Scorpio and is aspected by Mars, one will kill animals, be base, be a leader of robbers, be famous and be fond of (joining other) women, meat and wine. If Saturn is in Aries, or Scorpio and is aspected by Mercury, one will be untruthful, not virtuous, will eat much, be a famous thief and be devoid of happiness and riches. If Saturn is in Aries, or Scorpio and is aspected by Jupiter, one will be endowed with happiness, wealth and fortune,",
    "1": "/LIBRA IN ASPECT TO OTHERS. Should Saturn be in a Sign of Venus and is aspected by the Sun, the native will be clear in speech, will lose wealth, be a scholar, will eat in other's houses and be weak in constitution. If Saturn is in Taurus, or Libra and is aspected by the Moon, one will gain wealth through women, will be honoured by ministers of kings, be dear to women and be endowed with family. If Saturn is in Taurus, or Libra and is aspected by Mars, one will be skillful in war preparations, but will be away from war, will speak much and be endowed with wealth and family. If Saturn is in Tau",
    "2": "/VIRGO AND IN ASPECT TO OTHERS. If Saturn occupies a to a king, will possess a bright physique, will earn wealth and honour through women and will do women's jobs. If Saturn is in Gemini, or Virgo and is aspected by Mars, one will be a famous boxer, be stupefied, will carry heavy loads and will possess an ugly body. If Saturn is in Gemini, or Virgo and is aspected by Mercury, one will be rich, skillful in war, be a dance master, a skillful singer and an expert in arts. If Saturn is in Gemini, or Virgo and is aspected by Jupiter, one will be trustworthy in the king's circle, will possess all ki",
    "3": "If Saturn is in Cancer, one will possess a beloved wife, be devoid of wealth in boyhood, will suffer many diseases, be learned, motherless, soft-spoken, distinguished in acts, will always contract diseases, will trouble others, be inimical to relatives, crooked, be kingly in his mid-life and will enjoy growing pleasures. 9-10.",
    "4": "If Saturn occupies Leo, one will be interested in writing and reading, be skillful, be disdained, devoid of virtues and wife, will live by servitude, be devoid of his own men and happiness, be interested in doing base acts, ill-tempered, be mad with (undue) desires, will carry loads, will toil hard and will have a wrinkled body. 11-12.",
    "5": "If Saturn occupies Virgo at birth the subject will resemble a eunuch, be very crafty, will depend on others for food, be addicted to prostitutes, will have a few friends, be unacquainted with arts, be desirous of indulging in ugly acts, will possess sons and wealth, be indolent, helpful to others, will intent upon spoiling virgins and be cautious in his actions. 13-14. Saturn posited in Libra at birth indicates, that the subject will be rich, soft-spoken, will earn money and honours from foreign countries, be a king, or a scholar, will have his wealth protected by his relatives, be senior in t",
    "7": "If Saturn occupies Scorpio at birth, the native will be hostile, be crooked, affected by poison and weapons, very ill-tempered, miserly, egoistic, rich, capable of stealing others' money, averse to instruments played on festive occasions, malicious, very miserable and will face destruction, misery and diseases. 17-18.",
    "8": "If Saturn occupies Sagittarius, one will be skillful in behavior, teaching, Vedic meanings, learning and denotation, (i.e. he will be best placed in these respects), be famous due to virtuous children, family profession and his own virtues, will enjoy excellent affluence in his old age, will speak less, will have many names and be soft in disposition. 19-20. If Saturn is posited at birth in Capricorn, the native will lord over the lands of others' females, will be endowed with Vedic knowledge, virtues and knowledge of many branches of fine arts, be excellent among his caste-men, be honourable,",
    "11": "If Saturn occupies Pisces at birth, one will be fond of Sacrifices and arts, be chief among his relatives and friends, be calm, will have increasing wealth, be skillful in policy-making, be capable of diamond testing, be virtuous, modest and will later on acquire an authoritative position. 25-30."
  }
};
