// Offline city search over a bundled /cities.json (generated by
// scripts/gen-cities.mjs). Mirrors the /api/cities ranking (startsWith first,
// then contains, deduped, top 8) — but runs entirely in the browser.

interface City { name: string; province: string; country: string; lat: number; lng: number; tz: string; pop: number }

let cache: City[] | null = null;
let loading: Promise<City[]> | null = null;

async function load(): Promise<City[]> {
  if (cache) return cache;
  if (!loading) {
    loading = fetch("/cities.json")
      .then((r) => r.json())
      .then((d: City[]) => (cache = d))
      .catch(() => (cache = []));
  }
  return loading;
}

const norm = (s: string) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();

export async function searchCities(qRaw: string) {
  const q = norm(qRaw.trim());
  if (q.length < 2) return [];
  const all = await load();
  const starts: City[] = [], contains: City[] = [];
  for (const c of all) {
    const n = norm(c.name);
    if (n.startsWith(q)) starts.push(c);
    else if (n.includes(q)) contains.push(c);
    if (starts.length > 120) break;
  }
  const byPop = (a: City, b: City) => b.pop - a.pop;
  starts.sort(byPop); contains.sort(byPop);
  const seen = new Set<string>(), out: City[] = [];
  for (const c of [...starts, ...contains]) {
    const k = `${c.name.toLowerCase()}|${c.country}`;
    if (seen.has(k)) continue;
    seen.add(k); out.push(c);
    if (out.length >= 8) break;
  }
  return out.map(({ name, province, country, lat, lng, tz }) => ({ name, province, country, lat, lng, tz }));
}
